JNG-4511 Release cxf-jaxrs-application-manager
BlackBeltTechnology/cxf-jaxrs-application-manager pull request #42
Opened 2023-03-01 16:12 UTC by gaborflorian

…sion, eliminate warnings because set-output

2023-03-01 17:09 UTC, noherczeg approved these changes

2023-03-01 18:20 UTC, noherczeg requested changes

2023-03-01 18:20 UTC, noherczeg commented on pom.xml
> +                                    <licenseName>epl_v2</licenseName>
This is an apache license project, not EPL

2023-03-01 20:08 UTC, bencegelei approved these changes

2023-03-02 08:55 UTC, gaborflorian commented on pom.xml
> +                                    <licenseName>epl_v2</licenseName>
[b1cf05d](https://github.com/BlackBeltTechnology/cxf-jaxrs-application-manager/pull/42/commits/b1cf05dd9d2cf80b95c3a45b0e4de90949911cd7)

2023-03-02 19:43 UTC, robertcsakany approved these changes

2023-03-06 11:19 UTC, bencegelei approved these changes

2023-03-09 11:52 UTC, merged